apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-token
  namespace: layered-products
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: art/prod/jenkins/openshift-bot-token
      metadataPolicy: None
    secretKey: token
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: main-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: github-token
