apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'art-acm-tenant'
spec:
  project: default
  source:
    repoURL: 'https://github.com/openshift-eng/art-tools'
    path: art-cluster/pipelines/config/argocd/project/art-acm-tenant
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: art-acm-tenant
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
