apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'aws-sync-secrets'
spec:
  project: default
  source:
    repoURL: 'https://github.com/openshift-eng/art-config'
    path: clusters/artc2023/config/argocd/apps/art-aws-sync-secrets
    targetRevision: main
    directory:
      recurse: true
      jsonnet: { }
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: art-aws-sync-secrets
  syncPolicy:
    syncOptions:
      - PruneLast=true
