apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'layered-products'
spec:
  project: default
  source:
    repoURL: 'https://github.com/openshift-eng/art-tools'
    path: art-cluster/pipelines/config/argocd/project/layered-products
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: layered-products
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
