---
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.4
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks

  - repo: https://gitlab.cee.redhat.com/infosec-public/developer-workbench/tools.git
    rev: rh-pre-commit-2.3.0
    hooks:
      - id: rh-pre-commit

