apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  pipeline:
    default-timeout-minutes: 360
