apiVersion: v1
kind: Namespace
metadata:
  name: art-pipelines-ui
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
  annotations:
    openshift.io/display-name: ART Pipelines UI
    openshift.io/description: Search and rebuild ART tenant PipelineRuns
