apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: art-bot-config
  namespace: art-quay-tenant
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: art/prod/konflux/art-bot-config
      metadataPolicy: None
      property: slack-api-token
    secretKey: slack-api-token
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: art/prod/konflux/art-bot-config
      metadataPolicy: None
      property: slack-app-token
    secretKey: slack-app-token
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: main-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: art-bot-config
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: art-bot-docker-config
  namespace: art-quay-tenant
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: art/prod/konflux/art-bot-docker-config
      metadataPolicy: None
      property: config.json
    secretKey: config.json
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: main-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: art-bot-docker-config
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: doozer-config
  namespace: art-quay-tenant
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: art/prod/konflux/doozer-config
      metadataPolicy: None
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: main-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: doozer-config
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcp-sa-key
  namespace: art-quay-tenant
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: art/prod/konflux/gcp-sa-key
      metadataPolicy: None
      property: sa.json
    secretKey: sa.json
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: main-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: gcp-sa-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-app-credentials
  namespace: art-quay-tenant
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: art/prod/konflux/github-app-credentials
      metadataPolicy: None
      property: app-id
    secretKey: app-id
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: art/prod/konflux/github-app-credentials
      metadataPolicy: None
      property: private-key.pem
    secretKey: private-key.pem  # gitleaks:allow
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: main-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: github-app-credentials
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-token
  namespace: art-quay-tenant
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: art/prod/konflux/gitlab-token
      metadataPolicy: None
    secretKey: token
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: main-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: gitlab-token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: konflux-art-images-auth-file
  namespace: art-quay-tenant
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: art/prod/konflux/art-images-image-push
      metadataPolicy: None
      property: .dockerconfigjson
    secretKey: auth.json
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: main-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: konflux-art-images-auth-file
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: konflux-sa-kubeconfigs
  namespace: art-quay-tenant
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: art/prod/konflux/sa-tokens/konflux-bot-0-art-quay-tenant-sa
      metadataPolicy: None
    secretKey: quay
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: main-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: konflux-sa-kubeconfigs
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openshift-art-jira-bot-token
  namespace: art-quay-tenant
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: art/prod/konflux/jira-bot-token
      metadataPolicy: None
      property: token
    secretKey: token
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: main-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: openshift-art-jira-bot-token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openshift-bot-ssh-key
  namespace: art-quay-tenant
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: art/prod/konflux/openshift-bot-ssh-key
      metadataPolicy: None
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: main-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: openshift-bot-ssh-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-server-password
  namespace: art-quay-tenant
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: art/prod/konflux/redis-server-password
      metadataPolicy: None
      property: password
    secretKey: password
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: main-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: redis-server-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: synced-exd-ocp-buildvm-bot-prod-keytab
  namespace: art-quay-tenant
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: art/prod/exd-ocp-buildvm-bot-prod-keytab
      metadataPolicy: None
    secretKey: keytab
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: art/prod/exd-ocp-buildvm-bot-prod-keytab-principal
      metadataPolicy: None
      property: principal
    secretKey: principal
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: main-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: synced-exd-ocp-buildvm-bot-prod-keytab
