apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: art-quay-cronjob-viewer
  namespace: art-quay-tenant
rules:
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["get", "list", "watch"]
