apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: art-cd
  name: art-cd-base
spec:
  source:
    dockerfile: art-cluster/pipelines/data/project/art-cd/image/Containerfile.base
    git:
      ref: main
      uri: https://github.com/openshift-eng/art-tools
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: art-cluster/pipelines/data/project/art-cd/image/Containerfile.base
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: art-cd:latest
  successfulBuildsHistoryLimit: 10
  failedBuildsHistoryLimit: 5
  runPolicy: Serial
  triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secretReference:
          name: build-config-webhook-secret
