apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: validator-pipeline
  namespace: art-ci
spec:
  params:
    - description: github pr url
      name: pr_url
      type: string
    - description: github pr action
      name: pr_action
      type: string
  tasks:
    - name: validator-task
      params:
        - name: PR_link
          value: $(params.pr_url)
      taskRef:
        kind: Task
        name: validator-task
      when:
        - input: $(params.pr_action)
          operator: in
          values:
            - synchronize
            - opened
