import hashlib
import json
import typing
import uuid
from datetime import datetime
from enum import Enum

from google.cloud.bigquery.table import Row

from artcommonlib import logutil

LOGGER = logutil.get_logger(__name__)


class KonfluxBuildOutcome(Enum):
    FAILURE = 'failure'
    SUCCESS = 'success'


class ArtifactType(Enum):
    RPM = 'rpm'
    IMAGE = 'image'


class Engine(Enum):
    KONFLUX = 'konflux'
    BREW = 'brew'


class KonfluxBuild:
    """
    This class represents the data structure we use to store build information in Konflux
    By calling the konfluxdb.support.konflux_build.generate_build_schema() function,
    a table schema can be auto-generated from this class definition.
    The schema we get can then be injected into the konfluxdb.support.konflux_db.SupportKonfluxDb.create_table()
    function, that will create the table in BigQuery for us.

    In order for this to work, this class should contain no fields other than those we want to appear as table columns.
    """

    def __init__(self, name: str, group: str, version: str, release: str, assembly: str, el_target: str,
                 source_repo: str, commitish: str, embargoed: bool,
                 start_time: datetime, artifact_type: ArtifactType, engine: Engine,
                 end_time: datetime, image_tag: str, outcome: KonfluxBuildOutcome, job_url: str,
                 build_id: str = None, nvr: str = None):

        self.name = name
        self.group = group
        self.version = version
        self.release = release
        self.assembly = assembly
        self.el_target = el_target

        self.source_repo = source_repo
        self.commitish = commitish

        self.embargoed = embargoed

        self.artifact_type = artifact_type
        self.engine = engine

        self.start_time = start_time
        self.end_time = end_time

        self.image_tag = image_tag
        self.outcome = outcome
        self.job_url = job_url

        if not build_id:
            self.build_id = self.generate_uuid()

        if not nvr:
            self.nvr = self.nvr()

    def __str__(self):
        return json.dumps(self.to_dict(), indent=4)

    def to_dict(self) -> dict:
        """
        Returns a dict object representing the build data.
        KonfluxDb.add_builds() can use data in this form to store the build info into the DB.
        """

        return {
            key: (value.strftime("%Y-%m-%dT%H:%M:%S") if isinstance(value, datetime)
                  else value.value if isinstance(value, Enum) else value)
            for key, value in self.__dict__.items()
        }

    def generate_uuid(self) -> str:
        """
        The UUID is generated by hashing the string representation of a build object.
        Since it's very unlikely  that 2 different builds have the same exact fields,
        this should protect us from collisions.
        """

        build_repr = json.dumps(self.to_dict())
        hash_bytes = hashlib.sha256(build_repr.encode()).digest()
        return str(uuid.UUID(bytes=hash_bytes[:16]))

    def nvr(self):
        return f'{self.name}-{self.version}.{self.release}.assembly.{self.assembly}'


def from_result_row(row: Row) -> typing.Optional[KonfluxBuild]:
    """
    Given a google.cloud.bigquery.table.Row object, construct and return a KonfluxBuild object
    """

    try:
        return KonfluxBuild(**{
            field: (KonfluxBuildOutcome.SUCCESS if field == 'outcome' and row[field] == 'success' else row[field])
            for field in row.keys()
        })

    except AttributeError as e:
        LOGGER.error('Could not construct a KonfluxBuild object from result row %s: %s', row, e)
        raise
