from typing import Optional, Sequence

from pyartcd.cli import cli
from pyartcd.pipelines import (
    advisory_drop,
    art_notify,
    brew_scan_osh,
    build_fbc,
    build_merged_fbc,
    build_microshift,
    build_microshift_bootc,
    build_oadp,
    build_plashets,
    build_rhcos,
    build_sync,
    build_sync_multi,
    check_bugs,
    cleanup_locks,
    fbc_import_from_index,
    gen_assembly,
    images_health,
    oadp_scan_konflux,
    ocp,
    ocp4_konflux,
    ocp4_scan,
    ocp4_scan_konflux,
    okd,
    okd_images_health,
    olm_bundle,
    olm_bundle_konflux,
    operator_sdk_sync,
    prepare_release,
    prepare_release_konflux,
    promote,
    quay_doomsday_backup,
    rebuild,
    rebuild_golang_rpms,
    release_from_fbc,
    review_cvp,
    scan_fips,
    scan_for_kernel_bugs,
    scan_operator,
    scan_plashet_rpms,
    sigstore_sign,
    sync_rhcos_bfb,
    tag_rpms,
    tarball_sources,
    update_golang,
)
from pyartcd.pipelines.scheduled import (
    schedule_build_sync_multi,
    schedule_oadp_scan,
    schedule_ocp4_scan,
    schedule_ocp4_scan_konflux,
    schedule_scan_operator,
    schedule_scan_plashet_rpms,
)

__all__ = [
    "advisory_drop",
    "art_notify",
    "brew_scan_osh",
    "build_fbc",
    "build_merged_fbc",
    "build_microshift",
    "build_microshift_bootc",
    "build_oadp",
    "build_plashets",
    "build_rhcos",
    "build_sync",
    "build_sync_multi",
    "check_bugs",
    "cleanup_locks",
    "fbc_import_from_index",
    "gen_assembly",
    "images_health",
    "oadp_scan_konflux",
    "ocp",
    "ocp4_konflux",
    "ocp4_scan",
    "ocp4_scan_konflux",
    "okd",
    "okd_images_health",
    "olm_bundle",
    "olm_bundle_konflux",
    "operator_sdk_sync",
    "prepare_release",
    "prepare_release_konflux",
    "promote",
    "quay_doomsday_backup",
    "rebuild",
    "rebuild_golang_rpms",
    "release_from_fbc",
    "review_cvp",
    "scan_fips",
    "scan_for_kernel_bugs",
    "scan_operator",
    "scan_plashet_rpms",
    "sigstore_sign",
    "sync_rhcos_bfb",
    "tag_rpms",
    "tarball_sources",
    "update_golang",
    "schedule_build_sync_multi",
    "schedule_oadp_scan",
    "schedule_ocp4_scan",
    "schedule_ocp4_scan_konflux",
    "schedule_scan_operator",
    "schedule_scan_plashet_rpms",
]


def main(args: Optional[Sequence[str]] = None):
    # pylint: disable=no-value-for-parameter
    cli()


if __name__ == "__main__":
    main()
