apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-manager
  namespace: art-oap-tenant
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
rules:
- apiGroups:
  - external-secrets.io
  resources:
  - externalsecrets
  - secretstores
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - tekton.dev
  resources:
  - pipelines
  - tasks
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
