name: doozer-unit-tests

on:
  pull_request:
    paths:
      - 'doozer/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    container: fedora:37
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install packages
        run: cd doozer && dnf install -y gcc krb5-devel
      - name: Create venv and install dependencies
        run: cd doozer && make venv
      - name: Run tests
        run: cd doozer && make test