name: pyartcd-unit-tests

on:
  pull_request:
    paths:
      - 'pyartcd/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    container: fedora:37
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install packages
        run: cd pyartcd && dnf install -y gcc krb5-devel
      - name: Create venv and install dependencies
        run: cd pyartcd && make venv
      - name: Run tests
        run: cd pyartcd && make test